version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: openfoodfacts-mongo
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - openfoodfacts-net

  python:
    build: .
    container_name: openfoodfacts-python
    depends_on:
      - mongo
    volumes:
      - ./scripts:/app/scripts  # Mount scripts folder
      - ./domain:/app/domain
      - mongo_data:/data/db  # MongoDB storage
      - ./data:/app/data  # Store downloaded files
      - ./source_files:/app/source_files # Store source files
    networks:
      - openfoodfacts-net
    command: python -m scripts.collection_import
    
networks:
  openfoodfacts-net:
    driver: bridge

volumes:
  mongo_data: