version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: openfoodfacts-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - openfoodfacts-net

  python:
    build: .
    container_name: openfoodfacts-python
    depends_on:
      - mongo
    volumes:
      - ./scripts:/app  # Assuming your Python script is inside a `scripts` folder in the current directory
      - ./scripts:/app/scripts

    networks:
      - openfoodfacts-net
    command: python /app/import.py  # This will run the script when the container starts

networks:
  openfoodfacts-net:
    driver: bridge

volumes:
  mongo_data:
