version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: openfoodfacts-mongo
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - openfoodfacts-net

  python:
    build: .
    container_name: openfoodfacts-python
    depends_on:
      - mongo
    volumes:
      - ./scripts:/app/scripts  # Mount scripts folder
      - ./data:/app/data        # Mount the folder containing your CSV and JSON files
    networks:
      - openfoodfacts-net
    command: python /app/scripts/import.py  # Run script after build

networks:
  openfoodfacts-net:
    driver: bridge

volumes:
  mongo_data:
