from enum import IntEnum


class CategoryEnum(IntEnum):
    DAIRY_AND_EGG_PRODUCTS = 1
    SPICES_AND_HERBS = 2
    BABYFOODS = 3
    FATS_AND_OILS = 4
    POULTRY_PRODUCTS = 5
    SOUPS_SAUCES_AND_GRAVIES = 6
    SAUSAGES_AND_LUNCHEON_MEATS = 7
    BREAKFAST_CEREALS = 8
    FRUITS_AND_FRUIT_JUICES = 9
    PORK_PRODUCTS = 10
    VEGETABLES_AND_VEGETABLE_PRODUCTS = 11
    NUT_AND_SEED_PRODUCTS = 12
    BEEF_PRODUCTS = 13
    BEVERAGES = 14
    FINFISH_AND_SHELLFISH_PRODUCTS = 15
    LEGUMES_AND_LEGUME_PRODUCTS = 16
    LAMB_VEAL_AND_GAME = 17
    BAKED_PRODUCTS = 18
    SWEETS = 19
    CEREAL_GRAINS_AND_PASTA = 20
    FAST_FOODS = 21
    MEALS_ENTREES_AND_SIDE_DISHES = 22
    SNACKS = 23
    AMERICAN_INDIAN_ALASKA_NATIVE_FOODS = 24
    RESTAURANT_FOODS = 25
    BRANDED_FOOD_PRODUCTS_DATABASE = 26
    QUALITY_CONTROL_MATERIALS = 27
    ALCOHOLIC_BEVERAGES = 28
    OTHER = 29
